name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 #v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 #v8.7.0
        env:
          LINTER_RULES_PATH: .
          VALIDATE_BIOME_FORMAT: true
          VALIDATE_BIOME_LINT: true
          VALIDATE_CHECKOV: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_CPP: true
          VALIDATE_GITLEAKS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_PRE_COMMIT: true
          VALIDATE_SPELL_CODESPELL: true
          VALIDATE_TRIVY: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
